// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdSkBAAScbGTfqzyuLaQvF8Av0VpkooA',
    appId: '1:914878667575:web:4479a80fd5f9107d2498b2',
    messagingSenderId: '914878667575',
    projectId: 'weather-app-def49',
    authDomain: 'weather-app-def49.firebaseapp.com',
    storageBucket: 'weather-app-def49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAouTlsQPMRYwdzTcf8yL4HpVCHhgb4QGY',
    appId: '1:914878667575:android:f27c49d07d0b53b92498b2',
    messagingSenderId: '914878667575',
    projectId: 'weather-app-def49',
    storageBucket: 'weather-app-def49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpoMkHVt8aDeIl8hQhCvtx9gdD6AeZZc',
    appId: '1:914878667575:ios:8f93e4dd7a391d0b2498b2',
    messagingSenderId: '914878667575',
    projectId: 'weather-app-def49',
    storageBucket: 'weather-app-def49.appspot.com',
    androidClientId: '914878667575-laasbc1prj20ilnkkk58fkrqh70o2c7d.apps.googleusercontent.com',
    iosClientId: '914878667575-7p02vc1arg30k6e8j4ea8ncljg99rinf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpoMkHVt8aDeIl8hQhCvtx9gdD6AeZZc',
    appId: '1:914878667575:ios:8f93e4dd7a391d0b2498b2',
    messagingSenderId: '914878667575',
    projectId: 'weather-app-def49',
    storageBucket: 'weather-app-def49.appspot.com',
    androidClientId: '914878667575-laasbc1prj20ilnkkk58fkrqh70o2c7d.apps.googleusercontent.com',
    iosClientId: '914878667575-7p02vc1arg30k6e8j4ea8ncljg99rinf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWeather',
  );
}
